In [7]:
# Original 3x3 matrix
A = np.array([
    [-1, 0, 10],
    [6, 5, 2],
    [3, 33, 7],
], dtype=float)

q, r = qr(A)
print("Q=\n", q)
print('R=\n', r)

# Matrix size
n = A.shape[0]
#Construct Householder Reflection P1
V = A[1:, 0]#(Take first column below diagonal)
print("Vector(V)=", V)

# Compute norm of V
norm_V = np.linalg.norm(V)

# Choose alpha(we can choose any we want )
alpha = -np.sign(V[0]) * norm_V
print("alpha = ", alpha)

# First basis vector e1
e1 = np.zeros_like(V)
e1[0] = 1

# Construct Householder vector u
u = V - alpha * e1

# Normalize u(Normalized Householder vector u)
u = u / np.linalg.norm(u)
print("u=", u)

# Construct a small Householder matrix, P_small = I - 2uu^T
P1_small = np.eye(len(V)) - 2 * np.outer(u, u)
print("P_small:\n", P1_small)

# Embed into full matrix P1
P1 = np.eye(n)

# Insert P_small into lower-right block
P1[1:, 1:] = P1_small
print("P1:\n", P1) #full Householder matrix P1

# Transformed matrix A1,  A1 = P1^T A P1(from A to A1 by Embed into full matrix P1)
A1 = P1.T @ A @ P1
print("A1:\n", A1)

#second track 
#Construct Householder Reflection P2
# Now work on the lower-right 3x3 block of A1
# Take column 2 below the diagonal

V2 = A1[2:, 1] #(Take second column below diagonal)
print("V2=\n", V2) #Vector V2 (entries below a22)
norm_V2 = np.linalg.norm(V2)

# Choose alpha
alpha2 = -np.sign(V2[0]) * norm_V2
print("alpha2 = ", alpha2)

# Basis vector e1
e1_2 = np.zeros_like(V2)
e1_2[0] = 1

# Construct Householder vector
u2 = V2 - alpha2 * e1_2
u2 = u2 / np.linalg.norm(u2)
print("u2:\n", u2)

# Small Householder matrix
P2_small = np.eye(len(V2)) - 2 * np.outer(u2, u2)
print("P2_small:\n", P2_small)
# Embed into full 4x4 matrix
P2 = np.eye(n)

# Insert into lower-right corner
P2[2:, 2:] = P2_small
print("P2:\n", P2)

# Second similarity transformation
A2 = P2.T @ A1 @ P2
print("A2:\n", A2)

Q=
 [[-0.14744196  0.10224779  0.98377145]
 [ 0.88465174 -0.43118447  0.17740141]
 [ 0.44232587  0.89645153 -0.026879  ]]
R=
 [[ 6.78232998 19.02001234  3.39116499]
 [ 0.         27.42697815  6.43526965]
 [ 0.          0.         10.00436428]]
Vector(V)= [6. 3.]
alpha =  -6.708203932499369
u= [0.97324899 0.22975292]
P_small:
 [[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
P1:
 [[ 1.          0.          0.        ]
 [ 0.         -0.89442719 -0.4472136 ]
 [ 0.         -0.4472136   0.89442719]]
A1:
 [[-1.00000000e+00 -4.47213595e+00  8.94427191e+00]
 [-6.70820393e+00  1.94000000e+01  4.20000000e+00]
 [ 6.66133815e-16 -2.68000000e+01 -7.40000000e+00]]
V2=
 [-26.8]
alpha2 =  26.799999999999994
u2:
 [-1.]
P2_small:
 [[-1.]]
P2:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
A2:
 [[-1.00000000e+00 -4.47213595e+00 -8.94427191e+00]
 [-6.70820393e+00  1.94000000e+01 -4.20000000e+00]
 [-6.66133815e-16  2.68000000e+01 -7.40000000e+00]]


In [8]:
# Original 4x4 matrix
A = np.array([
    [9, 13, 3, 2],
    [1, 11, 4, 1],
    [3, 7, 4, 1],
    [6, 0, 7, 10]
], dtype=float)

q, r = qr(A)
print("Q=\n", q)
print('R=\n', r)

# Matrix size
n = A.shape[0]
#Construct Householder Reflection P1
V = A[1:, 0]#(Take first column below diagonal)
print("Vector(V)=", V)

# Compute norm of V
norm_V = np.linalg.norm(V)

# Choose alpha(we can choose any we want )
alpha = -np.sign(V[0]) * norm_V
print("alpha = ", alpha)

# First basis vector e1
e1 = np.zeros_like(V)
e1[0] = 1

# Construct Householder vector u
u = V - alpha * e1

# Normalize u(Normalized Householder vector u)
u = u / np.linalg.norm(u)
print("u=", u)

# Construct a small Householder matrix, P_small = I - 2uu^T
P1_small = np.eye(len(V)) - 2 * np.outer(u, u)
print("P_small:\n", P1_small)

# Embed into full matrix P1
P1 = np.eye(n)

# Insert P_small into lower-right block
P1[1:, 1:] = P1_small
print("P1:\n", P1) #full Householder matrix P1

# Transformed matrix A1,  A1 = P1^T A P1(from A to A1 by Embed into full matrix P1)
A1 = P1.T @ A @ P1
print("A1:\n", A1)

#second track 
#Construct Householder Reflection P2
# Now work on the lower-right 3x3 block of A1
# Take column 2 below the diagonal

V2 = A1[2:, 1] #(Take second column below diagonal)
print("V2=\n", V2) #Vector V2 (entries below a22)
norm_V2 = np.linalg.norm(V2)

# Choose alpha
alpha2 = -np.sign(V2[0]) * norm_V2
print("alpha2 = ", alpha2)

# Basis vector e1
e1_2 = np.zeros_like(V2)
e1_2[0] = 1

# Construct Householder vector
u2 = V2 - alpha2 * e1_2
u2 = u2 / np.linalg.norm(u2)
print("u2:\n", u2)

# Small Householder matrix
P2_small = np.eye(len(V2)) - 2 * np.outer(u2, u2)
print("P2_small:\n", P2_small)
# Embed into full 4x4 matrix
P2 = np.eye(n)

# Insert into lower-right corner
P2[2:, 2:] = P2_small
print("P2:\n", P2)

# Second similarity transformation
A2 = P2.T @ A1 @ P2
print("A2:\n", A2)

Q=
 [[-0.79862086 -0.19049605  0.56120143  0.10473267]
 [-0.08873565 -0.76690023 -0.4670494   0.4311089 ]
 [-0.26620695 -0.2716105  -0.30829646 -0.87196037]
 [-0.53241391  0.54936603 -0.60981235  0.2070297 ]]
R=
 [[-11.26942767 -13.22161199  -7.54253033  -7.27632338]
 [  0.         -12.81362464  -0.87996885   4.07415746]
 [  0.           0.          -5.6864656   -5.75106651]
 [  0.           0.           0.           1.83891084]]
Vector(V)= [1. 3. 6.]
alpha =  -6.782329983125268
u= [0.75744371 0.29198597 0.58397193]
P_small:
 [[-0.14744196 -0.44232587 -0.88465174]
 [-0.44232587  0.82948839 -0.34102322]
 [-0.88465174 -0.34102322  0.31795356]]
P1:
 [[ 1.          0.          0.          0.        ]
 [ 0.         -0.14744196 -0.44232587 -0.88465174]
 [ 0.         -0.44232587  0.82948839 -0.34102322]
 [ 0.         -0.88465174 -0.34102322  0.31795356]]
A1:
 [[ 9.00000000e+00 -5.01302651e+00 -3.94381755e+00 -1.18876351e+01]
 [-6.78232998e+00  1.28260870e+01 -1.78853182e+00  4.08991808e+00]
 

In [9]:
# Original 4x4 matrix
A = np.array([
    [37, 600, 13, 749, 2],
    [43, 11, 9,  4, 198],
    [3, 8888, 1000, 4, 400000],
    [777, 0, 68, 16, 10],
    [2, 5, 18, 66, 120]
], dtype=float)

q, r = qr(A)
print("Q=\n", q)
print('R=\n', r)

# Matrix size
n = A.shape[0]
#Construct Householder Reflection P1
V = A[1:, 0]#(Take first column below diagonal)
print("Vector(V)=", V)

# Compute norm of V
norm_V = np.linalg.norm(V)

# Choose alpha(we can choose any we want )
alpha = -np.sign(V[0]) * norm_V
print("alpha = ", alpha)

# First basis vector e1
e1 = np.zeros_like(V)
e1[0] = 1

# Construct Householder vector u
u = V - alpha * e1

# Normalize u(Normalized Householder vector u)
u = u / np.linalg.norm(u)
print("u=", u)

# Construct a small Householder matrix, P_small = I - 2uu^T
P1_small = np.eye(len(V)) - 2 * np.outer(u, u)
print("P_small:\n", P1_small)

# Embed into full matrix P1
P1 = np.eye(n)

# Insert P_small into lower-right block
P1[1:, 1:] = P1_small
print("P1:\n", P1) #full Householder matrix P1

# Transformed matrix A1,  A1 = P1^T A P1(from A to A1 by Embed into full matrix P1)
A1 = P1.T @ A @ P1
print("A1:\n", A1)

#second track 
#Construct Householder Reflection P2
# Now work on the lower-right 4x4 block of A1
# Take column 2 below the diagonal

V2 = A1[2:, 1] #(Take second column below diagonal)
print("V2=\n", V2) #Vector V2 (entries below a22)
norm_V2 = np.linalg.norm(V2)

# Choose alpha
alpha2 = -np.sign(V2[0]) * norm_V2
print("alpha2 = ", alpha2)

# Basis vector e1
e1_2 = np.zeros_like(V2)
e1_2[0] = 1

# Construct Householder vector
u2 = V2 - alpha2 * e1_2
u2 = u2 / np.linalg.norm(u2)
print("u2:\n", u2)

# Small Householder matrix
P2_small = np.eye(len(V2)) - 2 * np.outer(u2, u2)
print("P2_small:\n", P2_small)
# Embed into full 4x4 matrix
P2 = np.eye(n)

# Insert into lower-right corner
P2[2:, 2:] = P2_small
print("P2:\n", P2)

# Second similarity transformation
A2 = P2.T @ A1 @ P2
print("A2:\n", A2)

#Third track (5-2=3) three steps to 
#Construct Householder Reflection P3
# Now work on the lower-right 4x4 block of A3
# Take column 4 below the diagonal

V3 = A2[3:, 2] #(Take second column below diagonal)
print("V3=\n", V3) #Vector V2 (entries below a22)
norm_V3 = np.linalg.norm(V3)

# Choose alpha
alpha3 = -np.sign(V3[0]) * norm_V3
print("alpha3 = ", alpha3)

# Basis vector e1
e1_3 = np.zeros_like(V3)
e1_3[0] = 1

# Construct Householder vector
u3 = V3 - alpha3 * e1_3
u3 = u3 / np.linalg.norm(u3)
print("u3:\n", u3)

# Small Householder matrix
P3_small = np.eye(len(V3)) - 2 * np.outer(u3, u3)
print("P3_small:\n", P3_small)
# Embed into full 5x5 matrix
P3 = np.eye(n)

# Insert into lower-right corner
P3[3:, 3:] = P3_small
print("P3:\n", P3)

# third similarity transformation
A3 = P3.T @ A2 @ P3
print("A3:\n", A3)

Q=
 [[-4.74921344e-02  6.70174029e-02  9.52495758e-01  2.93006866e-01
  -1.23276845e-02]
 [-5.51935616e-02  8.42389792e-04 -6.87485543e-02  1.73074764e-01
  -9.80954496e-01]
 [-3.85071360e-03  9.97726101e-01 -6.40534454e-02 -2.05227966e-02
   1.94159106e-03]
 [-9.97334823e-01 -7.09154575e-03 -4.05666868e-02 -2.58704893e-02
   5.43877006e-02]
 [-2.56714240e-03  5.43038806e-04 -2.86839618e-01  9.39734875e-01
   1.86049759e-01]]
R=
 [[-7.79076376e+02 -6.33403881e+01 -7.28298300e+01 -5.19345744e+01
  -1.56159016e+03]
 [ 0.00000000e+00  8.90801201e+03  9.98132459e+02  5.41126845e+01
   3.99090736e+05]
 [ 0.00000000e+00  0.00000000e+00 -6.02113854e+01  6.93307633e+02
  -2.56679118e+04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.81680924e+02
  -8.06175434e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   6.05252627e+02]]
Vector(V)= [ 43.   3. 777.   2.]
alpha =  -778.1972757598165
u= [0.72638004 0.00265361 0.68728587 0.00176908]
P_small:
 [[-5.52559118e-02 -3

In [10]:
a = np.array([[0, 2], 
              [2, 3]])
p = [1, 5, 10, 20]
for i in range(20):
    q, r = qr(a)
    a = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(a)

Iteration 1:
[[3. 2.]
 [2. 0.]]
Iteration 5:
[[ 3.99998093  0.00976559]
 [ 0.00976559 -0.99998093]]
Iteration 10:
[[ 4.00000000e+00  9.53674316e-06]
 [ 9.53674316e-06 -1.00000000e+00]]
Iteration 20:
[[ 4.00000000e+00  9.09492929e-12]
 [ 9.09494702e-12 -1.00000000e+00]]
